version: '2'
services:

  flask-app:
    #    build: .
    image: hendisantika/flask-mysql-app:latest
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db

  db:
    #    build: db/.
    image: mysql:latest
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root